AMPs for emails and phones
SUNET/eduid-proofing-amp pull request #4
Opened 2017-06-28 12:21 UTC by enriquepablo

AMPs for emails and phones

2017-06-28 15:21 UTC, johanlundberg requested changes

2017-06-28 15:21 UTC, johanlundberg commented on eduid_proofing_amp/__init__.py
> +            'mail_addresses',
The attribute in the data dict is still called mailAliases.

2017-06-28 15:21 UTC, johanlundberg commented on eduid_proofing_amp/__init__.py
> +            'phone_numbers',
As above, the attribute in the data dict is called mobile.

2017-06-28 15:21 UTC, johanlundberg commented on eduid_proofing_amp/__init__.py
> +            'mail',  # Old format
mail is no longer an attribute for the new users.

2017-06-29 08:00 UTC, enriquepablo commented on eduid_proofing_amp/__init__.py
> +            'mail',  # Old format
Yes I mistook the attributes

2017-06-29 11:04 UTC, johanlundberg approved these changes

2017-06-29 11:04 UTC, merged